/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: wiringPiI2C.h

package I2C

import "unsafe"
import _ "runtime/cgo"
import "sync"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)

type _ unsafe.Pointer

var Swig_escape_always_false bool
var Swig_escape_val interface{}

type _swig_fnptr *byte
type _swig_memberptr *byte

type _ sync.Mutex

var _wrap_Swig_free_wiringPi_f2ed42202b4595ef unsafe.Pointer

func _swig_wrap_Swig_free(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Swig_free_wiringPi_f2ed42202b4595ef, _swig_p)
	return
}

func Swig_free(arg1 uintptr) {
	_swig_wrap_Swig_free(arg1)
}

var _wrap_Swig_malloc_wiringPi_f2ed42202b4595ef unsafe.Pointer

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_Swig_malloc_wiringPi_f2ed42202b4595ef, _swig_p)
	return
}

var _wrap_wiringPiI2CRead_wiringPi_f2ed42202b4595ef unsafe.Pointer

func WiringPiI2CRead(arg1 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_wiringPiI2CRead_wiringPi_f2ed42202b4595ef, _swig_p)
	return
}

var _wrap_wiringPiI2CReadReg8_wiringPi_f2ed42202b4595ef unsafe.Pointer

func WiringPiI2CReadReg8(arg1 int, arg2 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_wiringPiI2CReadReg8_wiringPi_f2ed42202b4595ef, _swig_p)
	return
}

var _wrap_wiringPiI2CReadReg16_wiringPi_f2ed42202b4595ef unsafe.Pointer

func WiringPiI2CReadReg16(arg1 int, arg2 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_wiringPiI2CReadReg16_wiringPi_f2ed42202b4595ef, _swig_p)
	return
}

var _wrap_wiringPiI2CWrite_wiringPi_f2ed42202b4595ef unsafe.Pointer

func WiringPiI2CWrite(arg1 int, arg2 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_wiringPiI2CWrite_wiringPi_f2ed42202b4595ef, _swig_p)
	return
}

var _wrap_wiringPiI2CWriteReg8_wiringPi_f2ed42202b4595ef unsafe.Pointer

func WiringPiI2CWriteReg8(arg1 int, arg2 int, arg3 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_wiringPiI2CWriteReg8_wiringPi_f2ed42202b4595ef, _swig_p)
	return
}

var _wrap_wiringPiI2CWriteReg16_wiringPi_f2ed42202b4595ef unsafe.Pointer

func WiringPiI2CWriteReg16(arg1 int, arg2 int, arg3 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_wiringPiI2CWriteReg16_wiringPi_f2ed42202b4595ef, _swig_p)
	return
}

var _wrap_wiringPiI2CSetupInterface_wiringPi_f2ed42202b4595ef unsafe.Pointer

func _swig_wrap_wiringPiI2CSetupInterface(base string, _ int) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiI2CSetupInterface_wiringPi_f2ed42202b4595ef, _swig_p)
	return
}

func WiringPiI2CSetupInterface(arg1 string, arg2 int) (_swig_ret int) {
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	return _swig_wrap_wiringPiI2CSetupInterface(arg1, arg2)
}

var _wrap_wiringPiI2CSetup_wiringPi_f2ed42202b4595ef unsafe.Pointer

func WiringPiI2CSetup(arg1 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_wiringPiI2CSetup_wiringPi_f2ed42202b4595ef, _swig_p)
	return
}

type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr
}

func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}
