/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

/* source: wiringPi.h */

#define SWIGMODULE wiringPi
/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef int intgo;
typedef unsigned int uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




static void *_swig_goallocate(size_t len) {
  struct {
    size_t len;
    void *ret;
  } SWIGSTRUCTPACKED a;
  a.len = len;
  crosscall2(_cgo_allocate, &a, (int) sizeof a);
  return a.ret;
}




/* This is here for backward compatibility, but it will not work
   with Go 1.5 or later.  Do not use it in new code.  */
static _gostring_ _swig_makegostring(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)_swig_goallocate(l + 1);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}

#ifdef __cplusplus
extern "C" {
#endif

void
_wrap_Swig_free_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  void *arg1 = (void *) 0 ;
  void *_swig_go_0;
  struct swigargs {
    void *arg1;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void
_wrap_Swig_malloc_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  void *result = 0 ;
  intgo _swig_go_0;
  void *_swig_go_result;
  char *swig_stktop;
  struct swigargs {
    intgo arg1;
    long : 0;
    void *result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = (int)_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_TRUE_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int result;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (1==1);
  
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_FALSE_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int result;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (!(1==1));
  
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_piModelNames_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  char **arg1 ;
  _gostring_* _swig_go_0;
  struct swigargs {
    _gostring_* arg1;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(char ***)&_swig_go_0; 
  
  {
    size_t ii;
    char const * *b = (char const * *) piModelNames;
    for (ii = 0; ii < (size_t)16; ii++) b[ii] = *((char const * *) arg1 + ii);
  }
  
}


void
_wrap_piModelNames_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  char **result = 0 ;
  _gostring_* _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    _gostring_* result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (char **)(char **)piModelNames;
  *(char ***)&_swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_piRevisionNames_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  char **arg1 ;
  _gostring_* _swig_go_0;
  struct swigargs {
    _gostring_* arg1;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(char ***)&_swig_go_0; 
  
  {
    size_t ii;
    char const * *b = (char const * *) piRevisionNames;
    for (ii = 0; ii < (size_t)16; ii++) b[ii] = *((char const * *) arg1 + ii);
  }
  
}


void
_wrap_piRevisionNames_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  char **result = 0 ;
  _gostring_* _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    _gostring_* result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (char **)(char **)piRevisionNames;
  *(char ***)&_swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_piMakerNames_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  char **arg1 ;
  _gostring_* _swig_go_0;
  struct swigargs {
    _gostring_* arg1;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(char ***)&_swig_go_0; 
  
  {
    size_t ii;
    char const * *b = (char const * *) piMakerNames;
    for (ii = 0; ii < (size_t)16; ii++) b[ii] = *((char const * *) arg1 + ii);
  }
  
}


void
_wrap_piMakerNames_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  char **result = 0 ;
  _gostring_* _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    _gostring_* result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (char **)(char **)piMakerNames;
  *(char ***)&_swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_piMemorySize_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int *result = 0 ;
  intgo *_swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    intgo *result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (int *)(int *)piMemorySize;
  *(int **)&_swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_WPI_FATAL_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int result;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (1==1);
  
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_WPI_ALMOST_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int result;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (1==2);
  
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiNodeStruct_pinBase_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  int arg2 ;
  struct wiringPiNodeStruct *_swig_go_0;
  intgo _swig_go_1;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    intgo arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->pinBase = arg2;
  
}


void
_wrap_wiringPiNodeStruct_pinBase_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  int result;
  struct wiringPiNodeStruct *_swig_go_0;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (int) ((arg1)->pinBase);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiNodeStruct_pinMax_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  int arg2 ;
  struct wiringPiNodeStruct *_swig_go_0;
  intgo _swig_go_1;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    intgo arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->pinMax = arg2;
  
}


void
_wrap_wiringPiNodeStruct_pinMax_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  int result;
  struct wiringPiNodeStruct *_swig_go_0;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (int) ((arg1)->pinMax);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiNodeStruct_fd_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  int arg2 ;
  struct wiringPiNodeStruct *_swig_go_0;
  intgo _swig_go_1;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    intgo arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  if (arg1) (arg1)->fd = arg2;
  
}


void
_wrap_wiringPiNodeStruct_fd_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  int result;
  struct wiringPiNodeStruct *_swig_go_0;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (int) ((arg1)->fd);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiNodeStruct_data0_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  unsigned int arg2 ;
  struct wiringPiNodeStruct *_swig_go_0;
  intgo _swig_go_1;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    intgo arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  
  if (arg1) (arg1)->data0 = arg2;
  
}


void
_wrap_wiringPiNodeStruct_data0_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  unsigned int result;
  struct wiringPiNodeStruct *_swig_go_0;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (unsigned int) ((arg1)->data0);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiNodeStruct_data1_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  unsigned int arg2 ;
  struct wiringPiNodeStruct *_swig_go_0;
  intgo _swig_go_1;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    intgo arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  
  if (arg1) (arg1)->data1 = arg2;
  
}


void
_wrap_wiringPiNodeStruct_data1_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  unsigned int result;
  struct wiringPiNodeStruct *_swig_go_0;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (unsigned int) ((arg1)->data1);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiNodeStruct_data2_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  unsigned int arg2 ;
  struct wiringPiNodeStruct *_swig_go_0;
  intgo _swig_go_1;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    intgo arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  
  if (arg1) (arg1)->data2 = arg2;
  
}


void
_wrap_wiringPiNodeStruct_data2_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  unsigned int result;
  struct wiringPiNodeStruct *_swig_go_0;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (unsigned int) ((arg1)->data2);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiNodeStruct_data3_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  unsigned int arg2 ;
  struct wiringPiNodeStruct *_swig_go_0;
  intgo _swig_go_1;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    intgo arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  arg2 = (unsigned int)_swig_go_1; 
  
  if (arg1) (arg1)->data3 = arg2;
  
}


void
_wrap_wiringPiNodeStruct_data3_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  unsigned int result;
  struct wiringPiNodeStruct *_swig_go_0;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (unsigned int) ((arg1)->data3);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiNodeStruct_pinMode_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  void (*arg2)(struct wiringPiNodeStruct *,int,int) = (void (*)(struct wiringPiNodeStruct *,int,int)) 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  void* _swig_go_1;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    void* arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  arg2 = *(void (**)(struct wiringPiNodeStruct *,int,int))&_swig_go_1; 
  
  if (arg1) (arg1)->pinMode = arg2;
  
}


void
_wrap_wiringPiNodeStruct_pinMode_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  void (*result)(struct wiringPiNodeStruct *,int,int) = 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  void* _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    long : 0;
    void* result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (void (*)(struct wiringPiNodeStruct *,int,int)) ((arg1)->pinMode);
  *(void (**)(struct wiringPiNodeStruct *,int,int))&_swig_go_result = (void (*)(struct wiringPiNodeStruct *,int,int))result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiNodeStruct_pullUpDnControl_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  void (*arg2)(struct wiringPiNodeStruct *,int,int) = (void (*)(struct wiringPiNodeStruct *,int,int)) 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  void* _swig_go_1;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    void* arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  arg2 = *(void (**)(struct wiringPiNodeStruct *,int,int))&_swig_go_1; 
  
  if (arg1) (arg1)->pullUpDnControl = arg2;
  
}


void
_wrap_wiringPiNodeStruct_pullUpDnControl_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  void (*result)(struct wiringPiNodeStruct *,int,int) = 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  void* _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    long : 0;
    void* result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (void (*)(struct wiringPiNodeStruct *,int,int)) ((arg1)->pullUpDnControl);
  *(void (**)(struct wiringPiNodeStruct *,int,int))&_swig_go_result = (void (*)(struct wiringPiNodeStruct *,int,int))result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiNodeStruct_digitalRead_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  int (*arg2)(struct wiringPiNodeStruct *,int) = (int (*)(struct wiringPiNodeStruct *,int)) 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  void* _swig_go_1;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    void* arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  arg2 = *(int (**)(struct wiringPiNodeStruct *,int))&_swig_go_1; 
  
  if (arg1) (arg1)->digitalRead = arg2;
  
}


void
_wrap_wiringPiNodeStruct_digitalRead_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  int (*result)(struct wiringPiNodeStruct *,int) = 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  void* _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    long : 0;
    void* result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (int (*)(struct wiringPiNodeStruct *,int)) ((arg1)->digitalRead);
  *(int (**)(struct wiringPiNodeStruct *,int))&_swig_go_result = (int (*)(struct wiringPiNodeStruct *,int))result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiNodeStruct_digitalWrite_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  void (*arg2)(struct wiringPiNodeStruct *,int,int) = (void (*)(struct wiringPiNodeStruct *,int,int)) 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  void* _swig_go_1;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    void* arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  arg2 = *(void (**)(struct wiringPiNodeStruct *,int,int))&_swig_go_1; 
  
  if (arg1) (arg1)->digitalWrite = arg2;
  
}


void
_wrap_wiringPiNodeStruct_digitalWrite_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  void (*result)(struct wiringPiNodeStruct *,int,int) = 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  void* _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    long : 0;
    void* result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (void (*)(struct wiringPiNodeStruct *,int,int)) ((arg1)->digitalWrite);
  *(void (**)(struct wiringPiNodeStruct *,int,int))&_swig_go_result = (void (*)(struct wiringPiNodeStruct *,int,int))result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiNodeStruct_pwmWrite_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  void (*arg2)(struct wiringPiNodeStruct *,int,int) = (void (*)(struct wiringPiNodeStruct *,int,int)) 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  void* _swig_go_1;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    void* arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  arg2 = *(void (**)(struct wiringPiNodeStruct *,int,int))&_swig_go_1; 
  
  if (arg1) (arg1)->pwmWrite = arg2;
  
}


void
_wrap_wiringPiNodeStruct_pwmWrite_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  void (*result)(struct wiringPiNodeStruct *,int,int) = 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  void* _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    long : 0;
    void* result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (void (*)(struct wiringPiNodeStruct *,int,int)) ((arg1)->pwmWrite);
  *(void (**)(struct wiringPiNodeStruct *,int,int))&_swig_go_result = (void (*)(struct wiringPiNodeStruct *,int,int))result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiNodeStruct_analogRead_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  int (*arg2)(struct wiringPiNodeStruct *,int) = (int (*)(struct wiringPiNodeStruct *,int)) 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  void* _swig_go_1;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    void* arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  arg2 = *(int (**)(struct wiringPiNodeStruct *,int))&_swig_go_1; 
  
  if (arg1) (arg1)->analogRead = arg2;
  
}


void
_wrap_wiringPiNodeStruct_analogRead_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  int (*result)(struct wiringPiNodeStruct *,int) = 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  void* _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    long : 0;
    void* result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (int (*)(struct wiringPiNodeStruct *,int)) ((arg1)->analogRead);
  *(int (**)(struct wiringPiNodeStruct *,int))&_swig_go_result = (int (*)(struct wiringPiNodeStruct *,int))result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiNodeStruct_analogWrite_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  void (*arg2)(struct wiringPiNodeStruct *,int,int) = (void (*)(struct wiringPiNodeStruct *,int,int)) 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  void* _swig_go_1;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    void* arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  arg2 = *(void (**)(struct wiringPiNodeStruct *,int,int))&_swig_go_1; 
  
  if (arg1) (arg1)->analogWrite = arg2;
  
}


void
_wrap_wiringPiNodeStruct_analogWrite_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  void (*result)(struct wiringPiNodeStruct *,int,int) = 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  void* _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    long : 0;
    void* result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (void (*)(struct wiringPiNodeStruct *,int,int)) ((arg1)->analogWrite);
  *(void (**)(struct wiringPiNodeStruct *,int,int))&_swig_go_result = (void (*)(struct wiringPiNodeStruct *,int,int))result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiNodeStruct_next_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  struct wiringPiNodeStruct *arg2 = (struct wiringPiNodeStruct *) 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  struct wiringPiNodeStruct *_swig_go_1;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    struct wiringPiNodeStruct *arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  arg2 = *(struct wiringPiNodeStruct **)&_swig_go_1; 
  
  if (arg1) (arg1)->next = arg2;
  
}


void
_wrap_wiringPiNodeStruct_next_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  struct wiringPiNodeStruct *result = 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  struct wiringPiNodeStruct *_swig_go_result;
  char *swig_stktop;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
    long : 0;
    struct wiringPiNodeStruct *result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (struct wiringPiNodeStruct *) ((arg1)->next);
  *(struct wiringPiNodeStruct **)&_swig_go_result = (struct wiringPiNodeStruct *)result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_new_wiringPiNodeStruct_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *result = 0 ;
  struct wiringPiNodeStruct *_swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    struct wiringPiNodeStruct *result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (struct wiringPiNodeStruct *)calloc(1, sizeof(struct wiringPiNodeStruct));
  *(struct wiringPiNodeStruct **)&_swig_go_result = (struct wiringPiNodeStruct *)result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_delete_wiringPiNodeStruct_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  
  free((char *) arg1);
  
}


void
_wrap_wiringPiNodes_set_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *arg1 = (struct wiringPiNodeStruct *) 0 ;
  struct wiringPiNodeStruct *_swig_go_0;
  struct swigargs {
    struct wiringPiNodeStruct *arg1;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(struct wiringPiNodeStruct **)&_swig_go_0; 
  
  wiringPiNodes = arg1;
  
}


void
_wrap_wiringPiNodes_get_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  struct wiringPiNodeStruct *result = 0 ;
  struct wiringPiNodeStruct *_swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    struct wiringPiNodeStruct *result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (struct wiringPiNodeStruct *)wiringPiNodes;
  *(struct wiringPiNodeStruct **)&_swig_go_result = (struct wiringPiNodeStruct *)result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiFailure_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  char *arg2 = (char *) 0 ;
  void *arg3 = 0 ;
  int result;
  intgo _swig_go_0;
  _gostring_ _swig_go_1;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    intgo arg1;
    _gostring_ arg2;
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = (int)_swig_go_0; 
  
  arg2 = (char *)malloc(_swig_go_1.n + 1);
  memcpy(arg2, _swig_go_1.p, _swig_go_1.n);
  arg2[_swig_go_1.n] = '\0';
  
  
  swig_stktop = _swig_topofstack();
  result = (int)wiringPiFailure(arg1,(char const *)arg2,arg3);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
  free(arg2); 
}


void
_wrap_wiringPiFindNode_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  struct wiringPiNodeStruct *result = 0 ;
  intgo _swig_go_0;
  struct wiringPiNodeStruct *_swig_go_result;
  char *swig_stktop;
  struct swigargs {
    intgo arg1;
    long : 0;
    struct wiringPiNodeStruct *result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = (int)_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (struct wiringPiNodeStruct *)wiringPiFindNode(arg1);
  *(struct wiringPiNodeStruct **)&_swig_go_result = (struct wiringPiNodeStruct *)result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiNewNode_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int arg2 ;
  struct wiringPiNodeStruct *result = 0 ;
  intgo _swig_go_0;
  intgo _swig_go_1;
  struct wiringPiNodeStruct *_swig_go_result;
  char *swig_stktop;
  struct swigargs {
    intgo arg1;
    intgo arg2;
    long : 0;
    struct wiringPiNodeStruct *result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  swig_stktop = _swig_topofstack();
  result = (struct wiringPiNodeStruct *)wiringPiNewNode(arg1,arg2);
  *(struct wiringPiNodeStruct **)&_swig_go_result = (struct wiringPiNodeStruct *)result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiSetup_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int result;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (int)wiringPiSetup();
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiSetupSys_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int result;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (int)wiringPiSetupSys();
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiSetupGpio_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int result;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (int)wiringPiSetupGpio();
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiSetupPhys_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int result;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (int)wiringPiSetupPhys();
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_pinModeAlt_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int arg2 ;
  intgo _swig_go_0;
  intgo _swig_go_1;
  struct swigargs {
    intgo arg1;
    intgo arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  pinModeAlt(arg1,arg2);
  
}


void
_wrap_pinMode_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int arg2 ;
  intgo _swig_go_0;
  intgo _swig_go_1;
  struct swigargs {
    intgo arg1;
    intgo arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  pinMode(arg1,arg2);
  
}


void
_wrap_pullUpDnControl_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int arg2 ;
  intgo _swig_go_0;
  intgo _swig_go_1;
  struct swigargs {
    intgo arg1;
    intgo arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  pullUpDnControl(arg1,arg2);
  
}


void
_wrap_digitalRead_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int result;
  intgo _swig_go_0;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    intgo arg1;
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = (int)_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (int)digitalRead(arg1);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_digitalWrite_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int arg2 ;
  intgo _swig_go_0;
  intgo _swig_go_1;
  struct swigargs {
    intgo arg1;
    intgo arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  digitalWrite(arg1,arg2);
  
}


void
_wrap_pwmWrite_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int arg2 ;
  intgo _swig_go_0;
  intgo _swig_go_1;
  struct swigargs {
    intgo arg1;
    intgo arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  pwmWrite(arg1,arg2);
  
}


void
_wrap_analogRead_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int result;
  intgo _swig_go_0;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    intgo arg1;
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = (int)_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (int)analogRead(arg1);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_analogWrite_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int arg2 ;
  intgo _swig_go_0;
  intgo _swig_go_1;
  struct swigargs {
    intgo arg1;
    intgo arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  analogWrite(arg1,arg2);
  
}


void
_wrap_wiringPiSetupPiFace_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int result;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (int)wiringPiSetupPiFace();
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiSetupPiFaceForGpioProg_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int result;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (int)wiringPiSetupPiFaceForGpioProg();
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_piBoardRev_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int result;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (int)piBoardRev();
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_piBoardId_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int *arg1 = (int *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  int *arg4 = (int *) 0 ;
  int *arg5 = (int *) 0 ;
  intgo *_swig_go_0;
  intgo *_swig_go_1;
  intgo *_swig_go_2;
  intgo *_swig_go_3;
  intgo *_swig_go_4;
  struct swigargs {
    intgo *arg1;
    intgo *arg2;
    intgo *arg3;
    intgo *arg4;
    intgo *arg5;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  _swig_go_2 = swig_a->arg3;
  _swig_go_3 = swig_a->arg4;
  _swig_go_4 = swig_a->arg5;
  arg1 = *(int **)&_swig_go_0; 
  arg2 = *(int **)&_swig_go_1; 
  arg3 = *(int **)&_swig_go_2; 
  arg4 = *(int **)&_swig_go_3; 
  arg5 = *(int **)&_swig_go_4; 
  
  piBoardId(arg1,arg2,arg3,arg4,arg5);
  
}


void
_wrap_wpiPinToGpio_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int result;
  intgo _swig_go_0;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    intgo arg1;
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = (int)_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (int)wpiPinToGpio(arg1);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_physPinToGpio_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int result;
  intgo _swig_go_0;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    intgo arg1;
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = (int)_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (int)physPinToGpio(arg1);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_setPadDrive_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int arg2 ;
  intgo _swig_go_0;
  intgo _swig_go_1;
  struct swigargs {
    intgo arg1;
    intgo arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  setPadDrive(arg1,arg2);
  
}


void
_wrap_getAlt_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int result;
  intgo _swig_go_0;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    intgo arg1;
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = (int)_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (int)getAlt(arg1);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_pwmToneWrite_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int arg2 ;
  intgo _swig_go_0;
  intgo _swig_go_1;
  struct swigargs {
    intgo arg1;
    intgo arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  pwmToneWrite(arg1,arg2);
  
}


void
_wrap_digitalWriteByte_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  intgo _swig_go_0;
  struct swigargs {
    intgo arg1;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = (int)_swig_go_0; 
  
  digitalWriteByte(arg1);
  
}


void
_wrap_digitalReadByte_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  unsigned int result;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (unsigned int)digitalReadByte();
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_pwmSetMode_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  intgo _swig_go_0;
  struct swigargs {
    intgo arg1;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = (int)_swig_go_0; 
  
  pwmSetMode(arg1);
  
}


void
_wrap_pwmSetRange_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  unsigned int arg1 ;
  intgo _swig_go_0;
  struct swigargs {
    intgo arg1;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = (unsigned int)_swig_go_0; 
  
  pwmSetRange(arg1);
  
}


void
_wrap_pwmSetClock_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  intgo _swig_go_0;
  struct swigargs {
    intgo arg1;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = (int)_swig_go_0; 
  
  pwmSetClock(arg1);
  
}


void
_wrap_gpioClockSet_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int arg2 ;
  intgo _swig_go_0;
  intgo _swig_go_1;
  struct swigargs {
    intgo arg1;
    intgo arg2;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  gpioClockSet(arg1,arg2);
  
}


void
_wrap_waitForInterrupt_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int arg2 ;
  int result;
  intgo _swig_go_0;
  intgo _swig_go_1;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    intgo arg1;
    intgo arg2;
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  swig_stktop = _swig_topofstack();
  result = (int)waitForInterrupt(arg1,arg2);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_wiringPiISR_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int arg2 ;
  void (*arg3)(void) = (void (*)(void)) 0 ;
  int result;
  intgo _swig_go_0;
  intgo _swig_go_1;
  void* _swig_go_2;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    intgo arg1;
    intgo arg2;
    void* arg3;
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  _swig_go_1 = swig_a->arg2;
  _swig_go_2 = swig_a->arg3;
  arg1 = (int)_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = *(void (**)(void))&_swig_go_2; 
  
  swig_stktop = _swig_topofstack();
  result = (int)wiringPiISR(arg1,arg2,arg3);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_piThreadCreate_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  void *(*arg1)(void *) = (void *(*)(void *)) 0 ;
  int result;
  void* _swig_go_0;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    void* arg1;
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = *(void *(**)(void *))&_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (int)piThreadCreate(arg1);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_piLock_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  intgo _swig_go_0;
  struct swigargs {
    intgo arg1;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = (int)_swig_go_0; 
  
  piLock(arg1);
  
}


void
_wrap_piUnlock_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  intgo _swig_go_0;
  struct swigargs {
    intgo arg1;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = (int)_swig_go_0; 
  
  piUnlock(arg1);
  
}


void
_wrap_piHiPri_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  int arg1 ;
  int result;
  intgo _swig_go_0;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    intgo arg1;
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = (int)_swig_go_0; 
  
  swig_stktop = _swig_topofstack();
  result = (int)piHiPri(arg1);
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_delay_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  unsigned int arg1 ;
  intgo _swig_go_0;
  struct swigargs {
    intgo arg1;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = (unsigned int)_swig_go_0; 
  
  delay(arg1);
  
}


void
_wrap_delayMicroseconds_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  unsigned int arg1 ;
  intgo _swig_go_0;
  struct swigargs {
    intgo arg1;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  _swig_go_0 = swig_a->arg1;
  arg1 = (unsigned int)_swig_go_0; 
  
  delayMicroseconds(arg1);
  
}


void
_wrap_millis_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  unsigned int result;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (unsigned int)millis();
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


void
_wrap_micros_wiringPi_cd4c57c2ec25305b(void *swig_v)
{
  unsigned int result;
  intgo _swig_go_result;
  char *swig_stktop;
  struct swigargs {
    long : 0;
    intgo result;
  } SWIGSTRUCTPACKED *swig_a = (struct swigargs *) swig_v;
  
  
  swig_stktop = _swig_topofstack();
  result = (unsigned int)micros();
  _swig_go_result = result; 
  swig_a = (struct swigargs*)((char*)swig_a + (_swig_topofstack() - swig_stktop));
  swig_a->result = _swig_go_result;
}


#ifdef __cplusplus
}
#endif

