/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: wiringPi.h

package wiringPi

import "unsafe"
import _ "runtime/cgo"
import "sync"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)

type _ unsafe.Pointer

var Swig_escape_always_false bool
var Swig_escape_val interface{}

type _swig_fnptr *byte
type _swig_memberptr *byte

type _ sync.Mutex

var _wrap_Swig_free_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_Swig_free(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Swig_free_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func Swig_free(arg1 uintptr) {
	_swig_wrap_Swig_free(arg1)
}

var _wrap_Swig_malloc_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_Swig_malloc_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_TRUE_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_getTRUE() (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_TRUE_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var TRUE int = _swig_getTRUE()
var _wrap_FALSE_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_getFALSE() (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_FALSE_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var FALSE int = _swig_getFALSE()

const WPI_MODE_PINS int = 0
const WPI_MODE_GPIO int = 1
const WPI_MODE_GPIO_SYS int = 2
const WPI_MODE_PHYS int = 3
const WPI_MODE_PIFACE int = 4
const WPI_MODE_UNINITIALISED int = -1
const INPUT int = 0
const OUTPUT int = 1
const PWM_OUTPUT int = 2
const GPIO_CLOCK int = 3
const SOFT_PWM_OUTPUT int = 4
const SOFT_TONE_OUTPUT int = 5
const PWM_TONE_OUTPUT int = 6
const LOW int = 0
const HIGH int = 1
const PUD_OFF int = 0
const PUD_DOWN int = 1
const PUD_UP int = 2
const PWM_MODE_MS int = 0
const PWM_MODE_BAL int = 1
const INT_EDGE_SETUP int = 0
const INT_EDGE_FALLING int = 1
const INT_EDGE_RISING int = 2
const INT_EDGE_BOTH int = 3
const PI_MODEL_A int = 0
const PI_MODEL_B int = 1
const PI_MODEL_AP int = 2
const PI_MODEL_BP int = 3
const PI_MODEL_2 int = 4
const PI_ALPHA int = 5
const PI_MODEL_CM int = 6
const PI_MODEL_07 int = 7
const PI_MODEL_3 int = 8
const PI_MODEL_ZERO int = 9
const PI_VERSION_1 int = 0
const PI_VERSION_1_1 int = 1
const PI_VERSION_1_2 int = 2
const PI_VERSION_2 int = 3
const PI_MAKER_SONY int = 0
const PI_MAKER_EGOMAN int = 1
const PI_MAKER_MBEST int = 2
const PI_MAKER_UNKNOWN int = 3

var _wrap_piModelNames_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_piModelNames_set(base *string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_piModelNames_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func SetPiModelNames(arg1 *string) {
	_swig_wrap_piModelNames_set(arg1)
}

var _wrap_piModelNames_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func GetPiModelNames() (_swig_ret *string) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_piModelNames_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_piRevisionNames_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_piRevisionNames_set(base *string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_piRevisionNames_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func SetPiRevisionNames(arg1 *string) {
	_swig_wrap_piRevisionNames_set(arg1)
}

var _wrap_piRevisionNames_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func GetPiRevisionNames() (_swig_ret *string) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_piRevisionNames_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_piMakerNames_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_piMakerNames_set(base *string) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_piMakerNames_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func SetPiMakerNames(arg1 *string) {
	_swig_wrap_piMakerNames_set(arg1)
}

var _wrap_piMakerNames_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func GetPiMakerNames() (_swig_ret *string) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_piMakerNames_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_piMemorySize_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func GetPiMemorySize() (_swig_ret *int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_piMemorySize_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_WPI_FATAL_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_getWPI_FATAL() (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_WPI_FATAL_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var WPI_FATAL int = _swig_getWPI_FATAL()
var _wrap_WPI_ALMOST_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_getWPI_ALMOST() (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_WPI_ALMOST_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var WPI_ALMOST int = _swig_getWPI_ALMOST()

type SwigcptrWiringPiNodeStruct uintptr

func (p SwigcptrWiringPiNodeStruct) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrWiringPiNodeStruct) SwigIsWiringPiNodeStruct() {
}

var _wrap_wiringPiNodeStruct_pinBase_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_pinBase_set(base SwigcptrWiringPiNodeStruct, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_pinBase_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) SetPinBase(arg2 int) {
	_swig_wrap_wiringPiNodeStruct_pinBase_set(arg1, arg2)
}

var _wrap_wiringPiNodeStruct_pinBase_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_pinBase_get(base SwigcptrWiringPiNodeStruct) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_pinBase_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) GetPinBase() (_swig_ret int) {
	return _swig_wrap_wiringPiNodeStruct_pinBase_get(arg1)
}

var _wrap_wiringPiNodeStruct_pinMax_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_pinMax_set(base SwigcptrWiringPiNodeStruct, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_pinMax_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) SetPinMax(arg2 int) {
	_swig_wrap_wiringPiNodeStruct_pinMax_set(arg1, arg2)
}

var _wrap_wiringPiNodeStruct_pinMax_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_pinMax_get(base SwigcptrWiringPiNodeStruct) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_pinMax_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) GetPinMax() (_swig_ret int) {
	return _swig_wrap_wiringPiNodeStruct_pinMax_get(arg1)
}

var _wrap_wiringPiNodeStruct_fd_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_fd_set(base SwigcptrWiringPiNodeStruct, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_fd_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) SetFd(arg2 int) {
	_swig_wrap_wiringPiNodeStruct_fd_set(arg1, arg2)
}

var _wrap_wiringPiNodeStruct_fd_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_fd_get(base SwigcptrWiringPiNodeStruct) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_fd_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) GetFd() (_swig_ret int) {
	return _swig_wrap_wiringPiNodeStruct_fd_get(arg1)
}

var _wrap_wiringPiNodeStruct_data0_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_data0_set(base SwigcptrWiringPiNodeStruct, _ uint) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_data0_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) SetData0(arg2 uint) {
	_swig_wrap_wiringPiNodeStruct_data0_set(arg1, arg2)
}

var _wrap_wiringPiNodeStruct_data0_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_data0_get(base SwigcptrWiringPiNodeStruct) (_ uint) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_data0_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) GetData0() (_swig_ret uint) {
	return _swig_wrap_wiringPiNodeStruct_data0_get(arg1)
}

var _wrap_wiringPiNodeStruct_data1_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_data1_set(base SwigcptrWiringPiNodeStruct, _ uint) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_data1_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) SetData1(arg2 uint) {
	_swig_wrap_wiringPiNodeStruct_data1_set(arg1, arg2)
}

var _wrap_wiringPiNodeStruct_data1_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_data1_get(base SwigcptrWiringPiNodeStruct) (_ uint) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_data1_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) GetData1() (_swig_ret uint) {
	return _swig_wrap_wiringPiNodeStruct_data1_get(arg1)
}

var _wrap_wiringPiNodeStruct_data2_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_data2_set(base SwigcptrWiringPiNodeStruct, _ uint) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_data2_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) SetData2(arg2 uint) {
	_swig_wrap_wiringPiNodeStruct_data2_set(arg1, arg2)
}

var _wrap_wiringPiNodeStruct_data2_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_data2_get(base SwigcptrWiringPiNodeStruct) (_ uint) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_data2_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) GetData2() (_swig_ret uint) {
	return _swig_wrap_wiringPiNodeStruct_data2_get(arg1)
}

var _wrap_wiringPiNodeStruct_data3_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_data3_set(base SwigcptrWiringPiNodeStruct, _ uint) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_data3_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) SetData3(arg2 uint) {
	_swig_wrap_wiringPiNodeStruct_data3_set(arg1, arg2)
}

var _wrap_wiringPiNodeStruct_data3_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_data3_get(base SwigcptrWiringPiNodeStruct) (_ uint) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_data3_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) GetData3() (_swig_ret uint) {
	return _swig_wrap_wiringPiNodeStruct_data3_get(arg1)
}

var _wrap_wiringPiNodeStruct_pinMode_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_pinMode_set(base SwigcptrWiringPiNodeStruct, _ _swig_fnptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_pinMode_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) SetPinMode(arg2 _swig_fnptr) {
	_swig_wrap_wiringPiNodeStruct_pinMode_set(arg1, arg2)
}

var _wrap_wiringPiNodeStruct_pinMode_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_pinMode_get(base SwigcptrWiringPiNodeStruct) (_ _swig_fnptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_pinMode_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) GetPinMode() (_swig_ret _swig_fnptr) {
	return _swig_wrap_wiringPiNodeStruct_pinMode_get(arg1)
}

var _wrap_wiringPiNodeStruct_pullUpDnControl_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_pullUpDnControl_set(base SwigcptrWiringPiNodeStruct, _ _swig_fnptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_pullUpDnControl_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) SetPullUpDnControl(arg2 _swig_fnptr) {
	_swig_wrap_wiringPiNodeStruct_pullUpDnControl_set(arg1, arg2)
}

var _wrap_wiringPiNodeStruct_pullUpDnControl_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_pullUpDnControl_get(base SwigcptrWiringPiNodeStruct) (_ _swig_fnptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_pullUpDnControl_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) GetPullUpDnControl() (_swig_ret _swig_fnptr) {
	return _swig_wrap_wiringPiNodeStruct_pullUpDnControl_get(arg1)
}

var _wrap_wiringPiNodeStruct_digitalRead_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_digitalRead_set(base SwigcptrWiringPiNodeStruct, _ _swig_fnptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_digitalRead_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) SetDigitalRead(arg2 _swig_fnptr) {
	_swig_wrap_wiringPiNodeStruct_digitalRead_set(arg1, arg2)
}

var _wrap_wiringPiNodeStruct_digitalRead_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_digitalRead_get(base SwigcptrWiringPiNodeStruct) (_ _swig_fnptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_digitalRead_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) GetDigitalRead() (_swig_ret _swig_fnptr) {
	return _swig_wrap_wiringPiNodeStruct_digitalRead_get(arg1)
}

var _wrap_wiringPiNodeStruct_digitalWrite_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_digitalWrite_set(base SwigcptrWiringPiNodeStruct, _ _swig_fnptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_digitalWrite_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) SetDigitalWrite(arg2 _swig_fnptr) {
	_swig_wrap_wiringPiNodeStruct_digitalWrite_set(arg1, arg2)
}

var _wrap_wiringPiNodeStruct_digitalWrite_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_digitalWrite_get(base SwigcptrWiringPiNodeStruct) (_ _swig_fnptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_digitalWrite_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) GetDigitalWrite() (_swig_ret _swig_fnptr) {
	return _swig_wrap_wiringPiNodeStruct_digitalWrite_get(arg1)
}

var _wrap_wiringPiNodeStruct_pwmWrite_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_pwmWrite_set(base SwigcptrWiringPiNodeStruct, _ _swig_fnptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_pwmWrite_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) SetPwmWrite(arg2 _swig_fnptr) {
	_swig_wrap_wiringPiNodeStruct_pwmWrite_set(arg1, arg2)
}

var _wrap_wiringPiNodeStruct_pwmWrite_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_pwmWrite_get(base SwigcptrWiringPiNodeStruct) (_ _swig_fnptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_pwmWrite_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) GetPwmWrite() (_swig_ret _swig_fnptr) {
	return _swig_wrap_wiringPiNodeStruct_pwmWrite_get(arg1)
}

var _wrap_wiringPiNodeStruct_analogRead_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_analogRead_set(base SwigcptrWiringPiNodeStruct, _ _swig_fnptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_analogRead_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) SetAnalogRead(arg2 _swig_fnptr) {
	_swig_wrap_wiringPiNodeStruct_analogRead_set(arg1, arg2)
}

var _wrap_wiringPiNodeStruct_analogRead_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_analogRead_get(base SwigcptrWiringPiNodeStruct) (_ _swig_fnptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_analogRead_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) GetAnalogRead() (_swig_ret _swig_fnptr) {
	return _swig_wrap_wiringPiNodeStruct_analogRead_get(arg1)
}

var _wrap_wiringPiNodeStruct_analogWrite_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_analogWrite_set(base SwigcptrWiringPiNodeStruct, _ _swig_fnptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_analogWrite_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) SetAnalogWrite(arg2 _swig_fnptr) {
	_swig_wrap_wiringPiNodeStruct_analogWrite_set(arg1, arg2)
}

var _wrap_wiringPiNodeStruct_analogWrite_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_analogWrite_get(base SwigcptrWiringPiNodeStruct) (_ _swig_fnptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_analogWrite_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) GetAnalogWrite() (_swig_ret _swig_fnptr) {
	return _swig_wrap_wiringPiNodeStruct_analogWrite_get(arg1)
}

var _wrap_wiringPiNodeStruct_next_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_next_set(base SwigcptrWiringPiNodeStruct, _ uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_next_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) SetNext(arg2 WiringPiNodeStruct) {
	_swig_wrap_wiringPiNodeStruct_next_set(arg1, arg2.Swigcptr())
}

var _wrap_wiringPiNodeStruct_next_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodeStruct_next_get(base SwigcptrWiringPiNodeStruct) (_ SwigcptrWiringPiNodeStruct) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodeStruct_next_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func (arg1 SwigcptrWiringPiNodeStruct) GetNext() (_swig_ret WiringPiNodeStruct) {
	return _swig_wrap_wiringPiNodeStruct_next_get(arg1)
}

var _wrap_new_wiringPiNodeStruct_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_new_wiringPiNodeStruct() (base SwigcptrWiringPiNodeStruct) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_new_wiringPiNodeStruct_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func NewWiringPiNodeStruct() (_swig_ret WiringPiNodeStruct) {
	return _swig_wrap_new_wiringPiNodeStruct()
}

var _wrap_delete_wiringPiNodeStruct_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_delete_wiringPiNodeStruct(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delete_wiringPiNodeStruct_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func DeleteWiringPiNodeStruct(arg1 WiringPiNodeStruct) {
	_swig_wrap_delete_wiringPiNodeStruct(arg1.Swigcptr())
}

type WiringPiNodeStruct interface {
	Swigcptr() uintptr
	SwigIsWiringPiNodeStruct()
	SetPinBase(arg2 int)
	GetPinBase() (_swig_ret int)
	SetPinMax(arg2 int)
	GetPinMax() (_swig_ret int)
	SetFd(arg2 int)
	GetFd() (_swig_ret int)
	SetData0(arg2 uint)
	GetData0() (_swig_ret uint)
	SetData1(arg2 uint)
	GetData1() (_swig_ret uint)
	SetData2(arg2 uint)
	GetData2() (_swig_ret uint)
	SetData3(arg2 uint)
	GetData3() (_swig_ret uint)
	SetPinMode(arg2 _swig_fnptr)
	GetPinMode() (_swig_ret _swig_fnptr)
	SetPullUpDnControl(arg2 _swig_fnptr)
	GetPullUpDnControl() (_swig_ret _swig_fnptr)
	SetDigitalRead(arg2 _swig_fnptr)
	GetDigitalRead() (_swig_ret _swig_fnptr)
	SetDigitalWrite(arg2 _swig_fnptr)
	GetDigitalWrite() (_swig_ret _swig_fnptr)
	SetPwmWrite(arg2 _swig_fnptr)
	GetPwmWrite() (_swig_ret _swig_fnptr)
	SetAnalogRead(arg2 _swig_fnptr)
	GetAnalogRead() (_swig_ret _swig_fnptr)
	SetAnalogWrite(arg2 _swig_fnptr)
	GetAnalogWrite() (_swig_ret _swig_fnptr)
	SetNext(arg2 WiringPiNodeStruct)
	GetNext() (_swig_ret WiringPiNodeStruct)
}

var _wrap_wiringPiNodes_set_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodes_set(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodes_set_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func SetWiringPiNodes(arg1 WiringPiNodeStruct) {
	_swig_wrap_wiringPiNodes_set(arg1.Swigcptr())
}

var _wrap_wiringPiNodes_get_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNodes_get() (base SwigcptrWiringPiNodeStruct) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNodes_get_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func GetWiringPiNodes() (_swig_ret WiringPiNodeStruct) {
	return _swig_wrap_wiringPiNodes_get()
}

var _wrap_wiringPiFailure_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiFailure(base int, _ string) (_ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiFailure_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func WiringPiFailure(arg1 int, arg2 string) (_swig_ret int) {
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return _swig_wrap_wiringPiFailure(arg1, arg2)
}

var _wrap_wiringPiFindNode_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiFindNode(base int) (_ SwigcptrWiringPiNodeStruct) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiFindNode_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func WiringPiFindNode(arg1 int) (_swig_ret WiringPiNodeStruct) {
	return _swig_wrap_wiringPiFindNode(arg1)
}

var _wrap_wiringPiNewNode_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_wiringPiNewNode(base int, _ int) (_ SwigcptrWiringPiNodeStruct) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_wiringPiNewNode_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func WiringPiNewNode(arg1 int, arg2 int) (_swig_ret WiringPiNodeStruct) {
	return _swig_wrap_wiringPiNewNode(arg1, arg2)
}

var _wrap_wiringPiSetup_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func WiringPiSetup() (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_wiringPiSetup_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_wiringPiSetupSys_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func WiringPiSetupSys() (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_wiringPiSetupSys_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_wiringPiSetupGpio_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func WiringPiSetupGpio() (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_wiringPiSetupGpio_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_wiringPiSetupPhys_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func WiringPiSetupPhys() (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_wiringPiSetupPhys_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_pinModeAlt_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_pinModeAlt(base int, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_pinModeAlt_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func PinModeAlt(arg1 int, arg2 int) {
	_swig_wrap_pinModeAlt(arg1, arg2)
}

var _wrap_pinMode_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_pinMode(base int, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_pinMode_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func PinMode(arg1 int, arg2 int) {
	_swig_wrap_pinMode(arg1, arg2)
}

var _wrap_pullUpDnControl_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_pullUpDnControl(base int, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_pullUpDnControl_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func PullUpDnControl(arg1 int, arg2 int) {
	_swig_wrap_pullUpDnControl(arg1, arg2)
}

var _wrap_digitalRead_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func DigitalRead(arg1 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_digitalRead_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_digitalWrite_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_digitalWrite(base int, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_digitalWrite_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func DigitalWrite(arg1 int, arg2 int) {
	_swig_wrap_digitalWrite(arg1, arg2)
}

var _wrap_pwmWrite_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_pwmWrite(base int, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_pwmWrite_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func PwmWrite(arg1 int, arg2 int) {
	_swig_wrap_pwmWrite(arg1, arg2)
}

var _wrap_analogRead_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func AnalogRead(arg1 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_analogRead_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_analogWrite_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_analogWrite(base int, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_analogWrite_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func AnalogWrite(arg1 int, arg2 int) {
	_swig_wrap_analogWrite(arg1, arg2)
}

var _wrap_wiringPiSetupPiFace_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func WiringPiSetupPiFace() (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_wiringPiSetupPiFace_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_wiringPiSetupPiFaceForGpioProg_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func WiringPiSetupPiFaceForGpioProg() (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_wiringPiSetupPiFaceForGpioProg_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_piBoardRev_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func PiBoardRev() (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_piBoardRev_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_piBoardId_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_piBoardId(base *int, _ *int, _ *int, _ *int, _ *int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_piBoardId_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func PiBoardId(arg1 *int, arg2 *int, arg3 *int, arg4 *int, arg5 *int) {
	_swig_wrap_piBoardId(arg1, arg2, arg3, arg4, arg5)
}

var _wrap_wpiPinToGpio_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func WpiPinToGpio(arg1 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_wpiPinToGpio_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_physPinToGpio_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func PhysPinToGpio(arg1 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_physPinToGpio_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_setPadDrive_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_setPadDrive(base int, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_setPadDrive_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func SetPadDrive(arg1 int, arg2 int) {
	_swig_wrap_setPadDrive(arg1, arg2)
}

var _wrap_getAlt_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func GetAlt(arg1 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_getAlt_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_pwmToneWrite_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_pwmToneWrite(base int, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_pwmToneWrite_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func PwmToneWrite(arg1 int, arg2 int) {
	_swig_wrap_pwmToneWrite(arg1, arg2)
}

var _wrap_digitalWriteByte_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_digitalWriteByte(base int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_digitalWriteByte_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func DigitalWriteByte(arg1 int) {
	_swig_wrap_digitalWriteByte(arg1)
}

var _wrap_digitalReadByte_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func DigitalReadByte() (_swig_ret uint) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_digitalReadByte_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_pwmSetMode_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_pwmSetMode(base int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_pwmSetMode_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func PwmSetMode(arg1 int) {
	_swig_wrap_pwmSetMode(arg1)
}

var _wrap_pwmSetRange_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_pwmSetRange(base uint) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_pwmSetRange_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func PwmSetRange(arg1 uint) {
	_swig_wrap_pwmSetRange(arg1)
}

var _wrap_pwmSetClock_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_pwmSetClock(base int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_pwmSetClock_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func PwmSetClock(arg1 int) {
	_swig_wrap_pwmSetClock(arg1)
}

var _wrap_gpioClockSet_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_gpioClockSet(base int, _ int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_gpioClockSet_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func GpioClockSet(arg1 int, arg2 int) {
	_swig_wrap_gpioClockSet(arg1, arg2)
}

var _wrap_waitForInterrupt_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func WaitForInterrupt(arg1 int, arg2 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_waitForInterrupt_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_wiringPiISR_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func WiringPiISR(arg1 int, arg2 int, arg3 _swig_fnptr) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_wiringPiISR_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_piThreadCreate_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func PiThreadCreate(arg1 _swig_fnptr) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_piThreadCreate_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_piLock_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_piLock(base int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_piLock_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func PiLock(arg1 int) {
	_swig_wrap_piLock(arg1)
}

var _wrap_piUnlock_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_piUnlock(base int) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_piUnlock_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func PiUnlock(arg1 int) {
	_swig_wrap_piUnlock(arg1)
}

var _wrap_piHiPri_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func PiHiPri(arg1 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_piHiPri_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_delay_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_delay(base uint) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delay_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func Delay(arg1 uint) {
	_swig_wrap_delay(arg1)
}

var _wrap_delayMicroseconds_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func _swig_wrap_delayMicroseconds(base uint) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_delayMicroseconds_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

func DelayMicroseconds(arg1 uint) {
	_swig_wrap_delayMicroseconds(arg1)
}

var _wrap_millis_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func Millis() (_swig_ret uint) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_millis_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

var _wrap_micros_wiringPi_cd4c57c2ec25305b unsafe.Pointer

func Micros() (_swig_ret uint) {
	_swig_p := uintptr(unsafe.Pointer(&_swig_ret))
	_cgo_runtime_cgocall(_wrap_micros_wiringPi_cd4c57c2ec25305b, _swig_p)
	return
}

type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr
}

func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}
