/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: wiringPiSPI.h

package wiringPiSPI

import "unsafe"
import _ "runtime/cgo"
import "sync"

var _cgo_runtime_cgocall func(unsafe.Pointer, uintptr)

type _ unsafe.Pointer

var Swig_escape_always_false bool
var Swig_escape_val interface{}

type _swig_fnptr *byte
type _swig_memberptr *byte

type _ sync.Mutex

var _wrap_Swig_free_wiringPiSPI_52ff6496c3824ae5 unsafe.Pointer

func _swig_wrap_Swig_free(base uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&base))
	_cgo_runtime_cgocall(_wrap_Swig_free_wiringPiSPI_52ff6496c3824ae5, _swig_p)
	return
}

func Swig_free(arg1 uintptr) {
	_swig_wrap_Swig_free(arg1)
}

var _wrap_Swig_malloc_wiringPiSPI_52ff6496c3824ae5 unsafe.Pointer

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_Swig_malloc_wiringPiSPI_52ff6496c3824ae5, _swig_p)
	return
}

var _wrap_wiringPiSPIGetFd_wiringPiSPI_52ff6496c3824ae5 unsafe.Pointer

func WiringPiSPIGetFd(arg1 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_wiringPiSPIGetFd_wiringPiSPI_52ff6496c3824ae5, _swig_p)
	return
}

var _wrap_wiringPiSPIDataRW_wiringPiSPI_52ff6496c3824ae5 unsafe.Pointer

func WiringPiSPIDataRW(arg1 int, arg2 *byte, arg3 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_wiringPiSPIDataRW_wiringPiSPI_52ff6496c3824ae5, _swig_p)
	return
}

var _wrap_wiringPiSPISetupMode_wiringPiSPI_52ff6496c3824ae5 unsafe.Pointer

func WiringPiSPISetupMode(arg1 int, arg2 int, arg3 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_wiringPiSPISetupMode_wiringPiSPI_52ff6496c3824ae5, _swig_p)
	return
}

var _wrap_wiringPiSPISetup_wiringPiSPI_52ff6496c3824ae5 unsafe.Pointer

func WiringPiSPISetup(arg1 int, arg2 int) (_swig_ret int) {
	_swig_p := uintptr(unsafe.Pointer(&arg1))
	_cgo_runtime_cgocall(_wrap_wiringPiSPISetup_wiringPiSPI_52ff6496c3824ae5, _swig_p)
	return
}

type SwigcptrVoid uintptr
type Void interface {
	Swigcptr() uintptr
}

func (p SwigcptrVoid) Swigcptr() uintptr {
	return uintptr(p)
}
